Segmentation on Clay
Clay-foundation/model pull request #257
Opened 2024-05-29 11:43 UTC by srmsoumya

Add segmentation support for Clay
- Head from Segformer paper: https://arxiv.org/abs/2105.15203
- Tested on a subset of Chesapeake Bay CVPR dataset with 7 classes

2024-06-04 14:00 UTC, yellowcap requested changes
Could you add some docs about how to download the Chesapeake dataset to fully run this independently?

2024-06-04 14:45 UTC, srmsoumya commented on finetune/segment/chesapeake_model.py
> +        ckpt_path="checkpoints/v0.5.7/mae_v0.5.7_epoch-13_val-loss-0.3098.ckpt",
Done.

2024-06-04 14:45 UTC, srmsoumya commented on configs/segment_chesapeake.yaml
> +  ckpt_path: checkpoints/v0.5.7/mae_v0.5.7_epoch-13_val-loss-0.3098.ckpt
Done.

2024-06-04 14:46 UTC, srmsoumya commented on configs/segment_chesapeake.yaml
> +        dirpath: s3://clay-model-ckpt/finetune/segment/chesapeake/v0.0.1/
Same as above.

2024-06-05 10:36 UTC, srmsoumya commented on finetune/segment/README.md
> +### Preparing the Dataset
@yellowcap we have details on how to prepare the dataset for segmentation task.

2024-06-05 13:11 UTC, yellowcap approved these changes
One small comment, otherwise looks good.

2024-06-05 13:11 UTC, yellowcap commented on finetune/segment/README.md
> +3. Update the WandB logger configuration in the configuration file with your WandB details:
Could we add instructions for folks that don't have wandb accounts?

2024-06-05 14:57 UTC, merged